language: python
python:
  - "2.7"
before_script:
  - mv CONFIG_SAMPLE.py CONFIG.py
script:
  - pep8 --max-line-length=120 bamboo_ipa_sync *.py
  - ./bamboo_ipa_sync -h
notifications:
  email:
    recipients:
      - peter@pakos.uk
