language: python
matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "2.7"
    env: TOXENV=pep8py2
  - python: "2.7"
    env: TOXENV=packagepy2
install:
  - pip install --upgrade pip setuptools wheel tox
script:
  - tox
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - peter@pakos.uk
